<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Unity.props" />
  <PropertyGroup><AssemblyName>MobileFPS.Gameplay</AssemblyName><DefineConstants>$(DefineConstants);</DefineConstants></PropertyGroup>
  <ItemGroup><Compile Include="$(SrcRoot)/Gameplay/**/*.cs" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../Core/Core.csproj" /></ItemGroup>
  
</Project>
